# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:

env:
  HEADASPROMPT: /dev/null # Allows non-interactive use of HEASoft tools
  UVOTREDUX_DATA_DIR: /mydata # Directory for UVOT data

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: robertdstein/heasoft:latest # Replace with your Docker image
      options: --user root

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Echo workspace
        run: |
          echo "Workspace is ${{ github.workspace }}"
          ls -la ${{ github.workspace }}

      - name: Install dependencies
        run: |
          pip install --upgrade coverage
          pip install -e ".[dev]"

      - name: Create data directory
        run: |
          mkdir -p $UVOTREDUX_DATA_DIR

      - name: Run tests
        working-directory: /mydata
        run: coverage run -m unittest discover ${{ github.workspace }}/tests

      - name: Run Coveralls
        continue-on-error: true
        if: ${{ success() }}
        run: |
          coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo tag name
        run: echo "Tag is ${{ github.ref }}, Tagged is ${{ startsWith(github.ref, 'refs/tags/')}},"

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Publish distribution 📦 to PyPI
        if: ${{ startsWith(github.ref, 'refs/tags/') && success() && github.event_name == 'push'}}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
