name: Test with Docker

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: robertdstein/heasoft:latest # Replace with your Docker image

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install -e ".[dev]"

      - name: Run tests
        run: python -m unittest discover tests
