name: Build and Publish Docker image

on:
  push:
  pull_request:

env:
  REGISTRY_IMAGE: robertdstein/uvotredux

jobs:
  push_to_registry:
    name: Build and Push Image for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata (version tag)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=ref,event=tag

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: ${{  startsWith(github.ref, 'refs/tags/') && github.event_name == 'push' }}
          tags: |
            ${{ env.REGISTRY_IMAGE }}:${{ matrix.platform }}-${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

  manifest:
    name: Create and Push Multi-Arch Manifest
    runs-on: ubuntu-latest
    needs: push_to_registry

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create and Push Manifest
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          IMAGE=${{ env.REGISTRY_IMAGE }}

          # Create and push versioned manifest
          docker manifest create $IMAGE:$VERSION \
            $IMAGE:linux/amd64-$VERSION \
            $IMAGE:linux/arm64-$VERSION

          docker manifest push $IMAGE:$VERSION

          # Also push latest tag pointing to same images
          docker manifest create $IMAGE:latest \
            $IMAGE:linux/amd64-$VERSION \
            $IMAGE:linux/arm64-$VERSION

          docker manifest push $IMAGE:latest


#  push_to_registry:
#    name: Build Docker image
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        platform: [linux/amd64, linux/arm64]
#    steps:
#      - name: Set up Docker
#        uses: docker/setup-docker-action@v4
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Check out the repo
#        uses: actions/checkout@v4
#
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#
#      - name: Extract metadata (tags, labels) for Docker
#        id: meta
#        uses: docker/metadata-action@v4
#        with:
#          images: ${{ env.REGISTRY_IMAGE }}
#
#      - name: Build Docker image
#        id: build
#        uses: docker/build-push-action@v4
#        with:
#          platforms: ${{ matrix.platform }}
#          context: .
#          file: ./Dockerfile
#          push: ${{  startsWith(github.ref, 'refs/tags/') && github.event_name == 'push' }}
#          tags: ${{ steps.meta.outputs.tags }}
#          labels: ${{ steps.meta.outputs.labels }}
